#!/bin/bash

# Current version
curl -O https://dl.google.com/go/go1.20.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.20.linux-amd64.tar.gz
rm go1.20.linux-amd64.tar.gz
